# Generated by Django 6.1 on 2026-10-04 01:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL, verbose_name='Blocked')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL, verbose_name='Blocker')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='safety_bloc_blocker_1d49e9_idx'), models.Index(fields=['blocked'], name='safety_bloc_blocked_26e97c_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment'), ('fake_profile', 'Fake Profile'), ('scam', 'Scam or Fraud'), ('spam', 'Spam'), ('other', 'Other')], max_length=30, verbose_name='Reason')),
                ('description', models.TextField(blank=True, verbose_name='Additional description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Reported user')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reporter'], name='safety_repo_reporte_90c1df_idx'), models.Index(fields=['reported'], name='safety_repo_reporte_5fb6e4_idx'), models.Index(fields=['reason'], name='safety_repo_reason_f5437f_idx'), models.Index(fields=['created_at'], name='safety_repo_created_ef0907_idx')],
            },
        ),
    ]
