# Generated by Django 4.2.30 on 2026-05-02 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('request', 'Request Chat'), ('reject', 'Reject')], max_length=10, verbose_name='Action')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('swipee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL, verbose_name='Swipee')),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL, verbose_name='Swiper')),
            ],
            options={
                'verbose_name': 'Swipe',
                'verbose_name_plural': 'Swipes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['swiper', 'swipee'], name='matching_sw_swiper__08211a_idx'), models.Index(fields=['swipee', 'action'], name='matching_sw_swipee__c06684_idx')],
                'unique_together': {('swiper', 'swipee')},
            },
        ),
    ]
