# Generated by Django 6.1 on 2026-10-04 01:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_requests', to=settings.AUTH_USER_MODEL, verbose_name='From user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_requests', to=settings.AUTH_USER_MODEL, verbose_name='To user')),
            ],
            options={
                'verbose_name': 'Chat Request',
                'verbose_name_plural': 'Chat Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user', 'to_user'], name='matching_ch_from_us_6174b6_idx'), models.Index(fields=['to_user', 'status'], name='matching_ch_to_user_55ca00_idx')],
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('request', 'Request Chat'), ('reject', 'Reject')], max_length=10, verbose_name='Action')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('swipee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_received', to=settings.AUTH_USER_MODEL, verbose_name='Swipee')),
                ('swiper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes_made', to=settings.AUTH_USER_MODEL, verbose_name='Swiper')),
            ],
            options={
                'verbose_name': 'Swipe',
                'verbose_name_plural': 'Swipes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['swiper', 'swipee'], name='matching_sw_swiper__08211a_idx'), models.Index(fields=['swipee', 'action'], name='matching_sw_swipee__c06684_idx')],
                'unique_together': {('swiper', 'swipee')},
            },
        ),
    ]
