# Generated by Django 4.2.30 on 2026-05-01 06:23

import apps.users.db.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_of_birth_remove_user_email_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[apps.users.db.user_model.User.validation_iran_phone_number], verbose_name='Phone number'),
        ),
    ]
