# Generated by Django 4.2.30 on 2026-05-02 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(max_length=10, unique=True, verbose_name='Province ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Province name')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=10, verbose_name='City ID')),
                ('name', models.CharField(max_length=100, verbose_name='City name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='users.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['province__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.city', verbose_name='City (Shahrestan)'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'name'], name='users_city_provinc_e7f3e0_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['city_id'], name='users_city_city_id_1dcd0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_id', 'province')},
        ),
    ]
