# Generated by Django 4.2.30 on 2026-05-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_province_city_user_province_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, through='users.UserInterest', to='users.interest', verbose_name='Interests'),
        ),
    ]
