# Generated by Django 4.2.30 on 2026-05-01 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='Message content')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Is edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
        ),
    ]
